use_frameworks!

platform :ios, '10.0'

target 'SimpleTools_Example' do
  pod 'SimpleTools/UserDefaultWrapper', :path => '../'

  target 'SimpleTools_Tests' do
    inherit! :search_paths

    
  end
end
